# Generated by Django 5.2 on 2025-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(default=2, upload_to="products/"),
            preserve_default=False,
        ),
    ]
