# Generated by Django 5.2 on 2025-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_image_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(upload_to="photos/", verbose_name="Изображение"),
        ),
    ]
